### ISSUE TITLE
title is not optional in dataset schema

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cell-census#108]
https://github.com/chanzuckerberg/cell-census/blob/7152b68c0b3e0debd1fc2b5200f1131bf26a00a0/tools/cell_census_builder/manifest.py#LL63C11-L63C86

`"dataset_title": dataset.get("title", ""),  # title is optional in schema
`

The comment is incorrect and the default value unnecessary. `title` is required in [uns](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#uns-dataset-metadata) because it is included in **Curators MUST annotate the following keys and values in uns.**

**Comment by pablo-gar** [comment]
Done
