### ISSUE TITLE
improve validation phase of census builder

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#11]
The "X" layer validation could be enhanced.  It currently performs checks on shape & nnz, but would benefit from content (value) checks as well.

**[Pablo @pablo-gar] proposal, the following validates the integrity of the data contents using 2 reference datasets ** 

  ~~For 2 Tabula Sapiens~~ All datasets perform the following validation steps:
  - [x] Count values for all cell metadata variables is equal between Cell Census and the original h5ads.
  - [ ] The sum values of X matrix is equal between Cell Census and the original dataset h5ads
  - [ ] The sum number of present genes in each h5ad dataset must be equal to the row sum of the corresponding datasets in the presence matrix.

Additional physical layer checks:
- [x] Verify that the entire census is a single directory tree (ie one root, with all data below that
- [x] Verify that the TileDB groups have all children stored with relative URIs (ie., the Group [is_relative flag](https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html#tiledb.Group.is_relative) is set to True)
- [x] Verify that obs, var and X layers are all fully consolidated & vacuumed (i.e., have a fragment count of 1)

**Comment by bkmartinjr** [comment]
A note on how to determine fragment count for a TileDB array -- use `tiledb.array_fragments`.

So for each SOMA object in question (e.g. experiment.obs), do the following:
> assert len(tiledb.array_fragments(experiment.obs.uri)) == 1

**Comment by Bento007** [comment]
> A note on how to determine fragment count for a TileDB array -- use `tiledb.array_fragments`.
> 
> So for each SOMA object in question (e.g. experiment.obs), do the following:
> 
> > assert len(tiledb.array_fragments(experiment.obs.uri)) == 1

Does need to be strictly == 1 or is >= 1 OK.

**Comment by bkmartinjr** [comment]
> Does it need to be strictly == 1 or is <= 1 OK.

Strictly 1

The point is that we want fragments to be consolidated into a single fragment, i.e., "==1"

**Comment by bkmartinjr** [comment]
> Strictly 1

note on this - I neglected to consider the case where the array was empty.  In that corner case, the fragment count would be zero.  I'll make a fix for this in my RC2 PR.  Apologies for the misdirect!

**Comment by bkmartinjr** [comment]
> Should I take this literally (as in sum all the values) or is there more nuance to this check?

I'm not sure who generated these requirements, so I'm not sure what they intended.  I'm guessing @pablo-gar based upon the description above  (which attributes the requirements to him).

That said, it doesn't make sense to sum the X matrix as this bug requests. To do the sum, you already have access to the data, so you might as well check for equality.  I'm unclear why one would do this for only two datasets when the existing code already reads the X matrices from all datasets to do the `nnz` comparison.

So you will need to ask @pablo-gar for clarification of his intent.  My guess is that he did not read the existing code before writing the requirement.

What I suggest: given that we already have all of the data in memory, I would replace the `nnz` check with a full check for equality. This will use somewhat more memory as you need to convert the COO data (from the SOMA object) into a format that can be compared to the AnnData, but that is a reasonable trade IMHO.

**Comment by Bento007** [comment]
removing 
>   - [ ] Count values for all gene metadata variables is equal between Cell Census and the original h5ads.

It doesn't provide any value to validation.

**Comment by pablo-gar** [comment]
> That said, it doesn't make sense to sum the X matrix as this bug requests. To do the sum, you already have access to the data, so you might as well check for equality. I'm unclear why one would do this for only two datasets when the existing code already reads the X matrices from all datasets to do the nnz comparison.

nnz  check -- it compares the number of non-zero elements. Insufficient for validity, as it not checks the actual values. 

The check here asks **to look at the integrity of the non-zero numerical values (not the count)** as they existed in the original data. The sum is a proxy for that, and doing it at the dataset level is for:

1. Efficiency, thus only 2, but if this is not an issue then we can do it for all datasets.
2. Compare directly from the data source (minimize processing from loading to when the comparison is done)

I believe it is a more robust validation if we do the comparison directly after loading from h5ad -- thus minimizing data manipulation.

--- 

Using equality for the validation requires you to make sure dimensions are properly ordered, but agreed it makes for a better check. The sum would be sufficient imo, the equality is very nice to have.
