### ISSUE TITLE
Validate additional fields in cell-census

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cell-census#133]
- Verify that the entire thing is a single directory tree (ie one root, with all data below that)
- Verify that the TileDB groups have all children stored with relative URIs (ie., the Group [is_relative flag](https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html#tiledb.Group.is_relative) is set to True)
- Add unit test for validator

**Comment by atolopko-czi** [comment]
Partial dup of #111 (bullet 1)

**Comment by Bento007** [comment]
removed duplicate requirement

**Comment by Bento007** [comment]
closing and add issues to #11
