### ISSUE TITLE
Refine Cell Census build instructions

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#134]
The build instructions under `cell-census/tools/cell_census_builder/` need to be refined and completed

- [x] Clean up prose and if needed add/modify instructions for them to be runnable
- [x] Include text indicating current cadence of build and schedule
- [x] Document current EC2 instance name use to build the Cell Census
- [x] Add instructions of how to upload to S3 after build process is complete.

**Comment by atolopko-czi** [comment]
Updated https://docs.google.com/document/d/12JwqpLWrm9_JbhEg99r7LB9sscevxL1gtliqu0s80Bo/edit#.

@Bento007 and @ebezzi As this is not a PR, I can only ask you for your review here. :)
Ideally, @Bento007, you will be able to run through these instructions for next build and perform an official test of them. For that reason, I'm going assign you to the story as well.

**Comment by pablo-gar** [comment]
would it be possible to include this instructions as an md document somewhere in the repo?

**Comment by atolopko-czi** [comment]
> would it be possible to include this instructions as an md document somewhere in the repo?

I don't think this is worth doing. This is still a fast-evolving document and contains CZI-internal details that we don't need to share w/anyone.

**Comment by atolopko-czi** [comment]
@ebezzi @Bento007 are instructions good enough now to close this issue?

**Comment by Bento007** [comment]
yes, but the document will continue to evolve.
