### ISSUE TITLE
Investigate potential improvements for validation of Cell Census contents

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#135]
The validation of the Cell Census build is very light weight, #11 has one proposal to expand this validation. An analysis to define if this is enough needs to be done, if deemed otherwise then proposed validation task need to be proposed.

Definition of done is -- if after solving #11 we got sufficient validation coverage then done, otherwise a list of validation task would complete this issue,

**Comment by Bento007** [comment]
- Verify that the entire thing is a single directory tree (ie one root, with all data below that)
- Verify that the TileDB groups have all children stored with relative URIs (ie., the Group [is_relative flag](https://tiledb-inc-tiledb.readthedocs-hosted.com/projects/tiledb-py/en/stable/python-api.html#tiledb.Group.is_relative) is set to True)
- Add unit test for validator

**Comment by pablo-gar** [comment]
This issue has caused more confusion than clarity, efforts should be focused on #11 as that has compiled all the work necessary.

Unless otherwise stated I will close this issue. cc @Bento007

**Comment by pablo-gar** [comment]
This issue has caused more confusion than clarity, efforts should be focused on #11 as that has compiled all the work necessary.

Unless otherwise stated I will close this issue. cc @Bento007
