### ISSUE TITLE
Python API adheres to requirements 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#137]
## Definition of Done
The API requirements are fulfilled by its functionalities, any functionality that doesn't contribute to the requirements is eliminated

**Comment by bkmartinjr** [comment]
@pablo-gar - can you expand on the requirements and/or desired functionality?  I can't quite tell from this issue what I need to do.

**Comment by pablo-gar** [comment]
It is currently blocked by #136. Once I finish it, this issue would just need to follow the directions of the API spec. Likely nothing to be done here since you did most of the cleaning on PR #117

**Comment by pablo-gar** [comment]
#135 has been closed with the final list of requirements which is here

https://docs.google.com/document/d/1sdyIFVPxXjie2r6SSKxALEABWod8rGmdDJkyyk_A8r0/edit#
