### ISSUE TITLE
Update repo README

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#143]
## Motivation

The README will serve as a splash page for any new comers to get a basic understanding of the Cell Census and start working with it.

This information will be migrated to a different location in the cellxgene.cziscience.com page

## Definition of Done

Update readme to comply with this [structure](https://docs.google.com/document/d/1FTwWN3AvTFDBD7zVb0IVbSUlYEhk28ZgP0wA1cBOvJU/edit#heading=h.6x8vnvqoodlv).

**Comment by bkmartinjr** [comment]
Please also remember that the cell-census PyPi package has its own repo in `api/python/cell_census/README.md`.  This is also publicly visible on PyPi, so should be updated as well, and kept largely synchronized with the repo readme.

Reference:   https://pypi.org/project/cell-census/

**Comment by pablo-gar** [comment]
Done #212
