### ISSUE TITLE
[DOCS] installation instructions for cell census are wrong

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#150]
The README contains obsolete and incorrect instructions for installation.

In particular `notebooks/REAMDE.md` is wrong, as it instructs the user to install from source which is going to create a lot of breakage.

The correct instructions should be to install from a release package on PyPi, ie.,

> pip install cell_census

CC: @pablo-gar @Ivana-Jelic @0seastar0

**Comment by Ivana-Jelic** [comment]
Thank you for letting us know, Bruce. I will remove the installation from the source instructions from my onboarding doc. 
I haven't yet shared that doc with any external users; they followed instructions from the GitHub repo.

**Comment by bkmartinjr** [comment]
Actually, I think we shoudl just fix it ASAP in the repo, and then your instructions are magically correct.

**Comment by Ivana-Jelic** [comment]
haha that works for me!

**Comment by pablo-gar** [comment]
Please include latest and stable installation instructions.
