### ISSUE TITLE
[FEATURE] census builder should drop a log file for later diagnostic use

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#162]
To make after-the-fact debugging easier, we should archive the verbose log from every census build that gets made public.  Ideally stash the log files in a shared bucket/directory with common naming, eg.,   `<census-tag-name>.log` or something like that.

It is very easy to set up the python logger to do this for "free", eg., change the logging `basicConfig` call to look something like:

```python
    log_file_path = os.path.join(args.out_dir, "pick-a-log-file-name.log")
    level = logging.DEBUG if verbose > 1 else logging.INFO if verbose == 1 else logging.WARNING
    logging.basicConfig(
        format="%(asctime)s %(process)-7s %(levelname)-8s %(message)s",
        level=level,
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file_path),
            logging.StreamHandler(sys.stdout),
        ],
    )
    logging.captureWarnings(True)
```

the key changes from the current code are the addition of the `handlers` args.

We then just need to standardize the location to stash logs.

**Comment by atolopko-czi** [comment]
We can use: s3://cellxgene-data-public-logs/builder/.  Used once so far to store logs (but not consistently). For now, I've added this to the manual instructions:
```
# Save logs for future troubleshooting needs
aws s3 cp build.log s3://cellxgene-data-public-logs/builder/<YYYY-MM-DD>.log
```

We can close this story under the assumption that future builder automation work will cover this: https://github.com/chanzuckerberg/cell-census/issues/110. (Added "upload logs" the requirements to be explicit.)

**Comment by bkmartinjr** [comment]
Agree.  Closing.
