### ISSUE TITLE
Cell Census builder uses TileDB-SOMA 1.0 RC

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#182]
If blocked by TileDB-SOMA 1.0 RC, then builder should use latest version by end of sprint.

This issue should be closed when TileDB-SOMA 1.0 RC is used for Cell Census builder.

**Comment by atolopko-czi** [comment]
Upgrading builder to RC branch appears to be trivial, as evidenced by diff in https://github.com/chanzuckerberg/cell-census/pull/210. However a full build will need to be tested, of course, before we can declare "it works" (assuming we _don't_ fix the PIT bug workaround, as that PR is attempting to do).
