### ISSUE TITLE
Dead code path in open_soma

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cell-census#202]
Is this path intentionally unreachable

https://github.com/chanzuckerberg/cell-census/blob/4485b64579b141b1b94e9005cb9f5fb5e26f638e/api/python/cell_census/src/cell_census/open.py#L23-L28

If this path should be accessible then #203 fixes it. Otherwise we can close this and the PR.

**Comment by bkmartinjr** [comment]
@Bento007 - I believe this was fixed.  Could you close if that is true?

**Comment by Bento007** [comment]
fixed by #203
