### ISSUE TITLE
Reference to CELLxGENE Discover data schema in Cell Census schema should be updated

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#21]
The Cell Census schema defines a "Cell Census table of CELLxGENE Discover datasets" – `census_obj[“census_info”][“datasets”]` – `SOMADataFrame`:

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>collection_id</td>
    <td>string</td>
    <td rowspan="5">As Defined in CELLxGENE Discover <a href="https://github.com/chanzuckerberg/single-cell/blob/main/design-documents/0001-data-portal-architecture/text.md#data-model">data schema</a>.</td>
  </tr>
  <tr>
    <td>collection_name</td>
    <td>string</td>
  </tr>
  <tr>
    <td>collection_doi</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_id</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_title</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_h5ad_path</td>
    <td>string</td>
    <td>Source h5ad file in the Cell Census storage bucket.</td>
  </tr>
  <tr>
    <td>dataset_total_cell_count</td>
    <td>int</td>
    <td>Total number of cells from the dataset included in the Cell Census.</td>
  </tr>
</tbody>
</table>

The link under "As Defined in CELLxGENE Discover [**data schema**](https://github.com/chanzuckerberg/single-cell/blob/main/design-documents/0001-data-portal-architecture/text.md#data-model)." points to an outdated schema.

This link should be fixed once an up-to-date "CELLxGENE Discover data schema" is available

**Comment by pablo-gar** [comment]
Work in progress

[https://lucid.app/lucidchart/8d085832-34f4-4413-9c1d-44e77d06e326/edit?page=0_0&invitationId=inv_ed354532-7256-4e0a-9ad0-b622905e5198#](https://www.google.com/url?q=https://lucid.app/lucidchart/8d085832-34f4-4413-9c1d-44e77d06e326/edit?page%3D0_0%26invitationId%3Dinv_ed354532-7256-4e0a-9ad0-b622905e5198%23&sa=D&source=docs&ust=1670083690292137&usg=AOvVaw122RyfqnvEkoRMNkGMAoeF)

**Comment by pablo-gar** [comment]
I don't have a strong opinion on the materialization of it so long as it is public and it defines the variables referenced in the table included in my original post

**Comment by atolopko-czi** [comment]
The data portal api docs change (model diagram) is not appearing in prod. Need to investigate/fix before we can close this issue.

**Comment by atolopko-czi** [comment]
@atarashansky If you closed this on purpose, please explain! :) I re-opened, since it's still broken.

**Comment by atarashansky** [comment]
It must have been in "ready for prod". I don't remember closing this.

**Comment by atolopko-czi** [comment]
Data Portal Discover API now displaying model diagram in production. Closing.
