### ISSUE TITLE
Properly handle zero values of sparse matrices from H5ADs

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#23]
A new requirement was added to the cell census schema.

> Per the CELLxGENE dataset schema, all [RNA assays MUST include UMI or read counts](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#x-matrix-layers). These counts MUST be encoded as `float32` in this `SOMASparseNdArray`. **`0` values in datasets with sparse matrices MUST not be explicitly encoded as `0`, they MUST be properly stored in sparse format.** 

@bkmartinjr Please make sure the cell census build adheres to this requirement OR close this issue if this is already happening

**Comment by bkmartinjr** [comment]
@pablo-gar - I need some clarification:
* I don't see a section in the linked (3.0 schema) doc that clearly addresses this requirement.  Is this requirement on zero-encoding specific to the cell census?
* As I read the above prose, you are asking for three separate things - to confirm:
    1. all X layer data encoded as a float32 sparse matrix
    2. the sparse matrix uses a matrix `fill` value of zero (ie, the values not materialized in memory are zero valued)
    3. there must be _no_ explicitly stored fill values (zero in our case)

just confirming this is your intent - in particular the third item, as that is where we deviate from the 3.0 cellxgene schema (which is silent on this point, allowing explicitly stored `fill` values)

**Comment by pablo-gar** [comment]
> * I don't see a section in the linked (3.0 schema) doc that clearly addresses this requirement.  Is this requirement on zero-encoding specific to the cell census?
> * As I read the above prose, you are asking for three separate things - to confirm:
>     1. all X layer data encoded as a float32 sparse matrix
>     2. the sparse matrix uses a matrix `fill` value of zero (ie, the values not materialized in memory are zero valued)
>     3. there must be _no_ explicitly stored fill values (zero in our case)

Correct, I had assumed 1 and 2 had been implemented, that leaves us to 3 which was recently added to the Cell Census schema

> just confirming this is your intent - in particular the third item, as that is where we deviate from the 3.0 cellxgene schema (which is silent on this point, allowing explicitly stored `fill` values)

Correct.

**Comment by bkmartinjr** [comment]
Thanks.  We get (3) "for free" in the current implementation, but it would be prudent to add validation in the census build tool. I will submit a PR for that, and close this issue when it is complete.

**Comment by bkmartinjr** [comment]
FYI - there _was_ an issue here, and the current census build has some explicitly stored zeros. I have a near-term fix in the works, and will re-build the census when it is fixed.
