### ISSUE TITLE
Create docker image for build

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cell-census#266]
## Motivation

Why is this work important to engineers?

## Definition of Done

What should the end result look like? What will have been changed?

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ]
- [ ]

**Comment by bkmartinjr** [comment]
this looks like a duplicate of #265

**Comment by ebezzi** [comment]
I will close this one in favor of #265
