### ISSUE TITLE
contact email is inconsistent

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#280]
Contact email address is variously listed as soma@ and cellxgene@ in different locations. Need to pick one.
* repo README.md
* Python package README and metadata
* R package REAMDE and metadata
* Builder package metadata
etc.

**Comment by pablo-gar** [comment]
soma@ should be used.

I will take care of the package READMEs as part of #230 and #231.

**Comment by bkmartinjr** [comment]
@mlin - tagging you for the R package metadata, etc.  I'll do Python.

**Comment by pablo-gar** [comment]
@mlin I've done the change for the R package at #282 just need your approval

**Comment by pablo-gar** [comment]
addressed #282 and #281
