### ISSUE TITLE
S3 read logs

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#34]
Access logs and plumbing to support analytics on the public data bucket.

Bucket name and prefix used for storing logs should be sufficiently generic to allow use for by SCB team to capture S3 logs for other public data.

**Comment by atolopko-czi** [comment]
Awaiting [Terrraform advice](https://czi-sci.slack.com/archives/C56QRGLRJ/p1670951378013839).

**Comment by atolopko-czi** [comment]
TF apply required two runs due s3 bucket creation timing, which caused previous run to fail. [2nd run](https://si.prod.tfe.czi.technology/app/single-cell-infra/workspaces/prod-soma/runs/run-qXrMYTNhsyBgGSza)
