### ISSUE TITLE
cell_census_builder: validate no dups

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#35]
Add validations that there are no duplicate indices in all Measurement Layers, for all Experiments:
* X[raw] - all (soma_dim_0, soma_dim_1) pairs are unique
* obs/var - all soma_joinid are unique
Then configure `allow_duplicates=True` (to improve TileDB performance). This requires parameterizing the `allow_duplicates` attribute via `platform_config` in TileDB-SOMA library.

The removal of `allow_duplicates` on the underlying array schemas provides a significant read performance improvement.

**Comment by atolopko-czi** [comment]
Replaced by https://github.com/chanzuckerberg/cell-census/issues/61
