### ISSUE TITLE
Include census builder git commit sha1 in census

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#39]
Options:
1. Include as metadata in the census SOMA object [metadata](https://github.com/chanzuckerberg/cell-census/blob/main/docs/cell_census_schema_0.0.1.md#cell-census-information-census_objcensus_info---somacollection).
2. Include as new file in the cell-census storage dir.
3. Include in `releases.json`. 

* Option 1 seems best, but requires a schema change.
* Option 2 is easiest, but a bit messy (adds a new, loose file).
* Option 3 would be reasonable if/when we automate updating of `releases.json`. Also, doesn't connect the git commit as tightly as other options.

**Comment by bkmartinjr** [comment]
Option 1 seems best to me. I don't think it requires a schema change, as long as it does not conflict with other schema fields.  There are already lots of other metadata stored in that collection for similar reasons, and not documented in the official schema.

**Comment by pablo-gar** [comment]
For the first option that Andrew mentions there may be some confusion as to what "metadata" we are referring to.

It could be interpreted for the sha1 to be included in either of:

a) `census["census_info"]["summary"]` as an extra row  -- This requires a schema change.
b) `census._metadata` as an extra key-value pair -- This does not require a schema change.

Currently `census._metadata` has the following keys `['census_schema_version', 'created_on', 'cxg_schema_version', 'soma_encoding_version', 'soma_object_type']`. These likely the metadata bruce is referring to.

**Comment by pablo-gar** [comment]
Can I get a brief explanation of the reason to include the sha1 commit in the the census build? I can give better guidance upon that. 

For example, is this intended only for internal purposes?

**Comment by atolopko-czi** [comment]
> Can I get a brief explanation of the reason to include the sha1 commit in the the census build?

1. Reproducibility: 1) "how exactly was this census built?" The sha1 provides the answer. 2) It can be used to infer which version of the API was can access the census, though we might want that to be a more explicit API release version than a SHA1
2. Internal: Troubleshooting any build issues, particularly between census builds where data may have changed in an unexpected way.  We can diff code between the builder SHA1s.

**Comment by atolopko-czi** [comment]
`census._metadata` sounds like the right place to me

**Comment by pablo-gar** [comment]
Got it! Thanks, and yes I agree with `census._metadata` for this uses. So let's go with that option.

Discussion -- Do you have a recommendation for where to document what's been stored `census._metadata` or do you think it is fine to leave it as self explanatory.? Most external users and some internal users are likely to be unaware of it.

**Comment by atolopko-czi** [comment]
> Do you have a recommendation for where to document what's been stored census._metadata or do you think it is fine to leave it as self explanatory.?

I don't think these fields will be self-explanatory to everyone, so documentation can't hurt.  I do see the issue with putting it in the schema doc itself, since this is metadata about the "physical" SOMA object and not the scientific data it embodies. So not strongly advocating for that. But I don't know where else to put this other than in a README in the repo. 

(Some of the existing `_metadata` fields *could* be part of the schema, arguably! E.g., it should be able to self-report its own version.  But this becomes a philosophical debate about the nature of the schema.)
