### ISSUE TITLE
Support running code checks locally

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#44]
Rather than waiting for GHA failures of `formatting.yml` job to catch linting & typing errors after pushing to Github, provide a script to allow developers to invoke these checks locally.

* Capture additional in requirements-dev.txt file
* Package checks into script, with option to make changes to source files.
* Be DRY w.r.t. GHA `formatting.yml` job (call into script)
* Consider running checks as a git commit or push hook

**Comment by bkmartinjr** [comment]
the first three items in the list are implemented.

@atolopko-czi - I leave it to you to decide if you close or leave open for the commit hook.

**Comment by atolopko-czi** [comment]
> the first three items in the list are implemented.
> 
> @atolopko-czi - I leave it to you to decide if you close or leave open for the commit hook.

the checks will run soon enough after a push, so good enough to call this issue done.
