### ISSUE TITLE
Separate `column_names` for obs and var as different arguments of `cell_census.get_anndata()`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cell-census#57]
For improved readability and usability please separate `column_names` of `cell_census.get_anndata()` into two arguments:

- `obs_column_names`: List[str]
- `var_column_names` : List[str]

This provides consistency with the already existing `obs_value_filter` and `var_value_filter` arguments.

**Comment by bkmartinjr** [comment]
This makes it inconsistent with the underlying (very draft) SOMA API.

Over time we'll need to decide if we are trying to maintain alignment between the two. We can revisit once the Query API stabilizes.

**Comment by bkmartinjr** [comment]
@pablo-gar - just confirming you still want this change made?  Or should we converge with the SOMA query API params?  LMK and I'll get it done.

**Comment by pablo-gar** [comment]
please converge with SOMA query params, and let's keep this model of minimizing divergence between Cell Census existing convenience functions and SOMA API

**Comment by bkmartinjr** [comment]
roger.

I also suggest that you raise UX issues with the SOMA API as you see them.  Community/user input is valuable at this point, and we _can_ make changes.  

Closing this issue.
