### ISSUE TITLE
builder: set allow_duplications to false for performance

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#61]
Motivation:
Census reads will be more performant if `allow_duplicates=True` is set on X arrays (in particular).

Goal:
All Census TileDB X layer arrays are configured with `allow_duplicates=True`. 

Note that this allows the SOMA spec and implementation to stay "as is", i.e. strictly maintaining "no dups" semantics, and places the burden on the Census builder to enact this optimization by overriding the SOMA TileDB dups setting for its special use case (i.e. write-once, read-many).

Design:
After building the census, post-compaction, the builder should use schema evolution to set `allow_duplicates=True`.  
By changing this setting _after_ compaction, we can rely upon the compaction to (quietly) remove any dup coords, thus maintaining the guarantee that X matrix layers will not have dups. 

Note that the existing validation logic already checks that each dataset's AnnData X counts are preserved in the stored census, and the validation runs post-compaction. So if compaction somehow dropped data due to de-duping, we still have a safety check in place to catch this.

Backup plan:
If the performance win is desired prior to the core DB supporting post-array configuration changes to this flag, we could emulate it with the following, as a _temporary_ work-around:
* override the creation process of the X layer to create an array with duplicates allowed.  This will require creating a TileDB array outside the SOMA package, in a manner that is compatible with the SOMA library expectations (primariily, that it has the correct metadata to indicate it as a soma type).
* responsibility for duplicate removal/consolidation would now lay with the cell census builder
The first step is hacky, and only suitable for a short-term work around.

**Comment by atolopko-czi** [comment]
Blocked by need for schema evolution support in TileDB-SOMA.

**Comment by bkmartinjr** [comment]
The necessary support to implement is available as of tiledbsoma==0.5.0a9.

**Comment by bkmartinjr** [comment]
@Bento007 - I"m going to explore adding this as part of the 1.0rc0 update (PR #154) as having it off is killing the builder performance (consolidation takes forever).

**Comment by bkmartinjr** [comment]
I have included a fix for this in #154
