### ISSUE TITLE
update Census API and Builder to tilebsoma 0.5.0a4

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#67]
Make updates to cell_census_builder for TileDB-SOMA changes introduce by:
* https://github.com/single-cell-data/TileDB-SOMA/issues/570 (query API)
* https://github.com/single-cell-data/TileDB-SOMA/issues/644 (explicit context)

- [x] @atolopko-czi complete #77
- [x] @atolopko-czi  will re-run (and fix, as needed) the `comp_bio_explore_and_load_lung_data.ipynb` notebook. This can be done as a follow-up PR to #77

**Comment by atolopko-czi** [comment]
@bkmartinjr Any objection if I also make API changes as needed while I'm fix builder breakages from TileDB-SOMA updates?

**Comment by bkmartinjr** [comment]
None - it would be appreciated.
