### ISSUE TITLE
Update dataset table information with external Corpora schema file

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cell-census#7]
The dataset table `census_obj[“census_info”][“datasets”]` of the Cell Census as defined in its schema has the following columns whose values are directly obtained from Corpora. 

- collection_id
- collection_name
- collection_doi
- dataset_id
- dataset_title

These values will be defined in their respective documents (see outdated documentation [here](https://public-backend.production.single-cell.czi.technology/curation/ui/&sa=D&source=docs&ust=1667856368698013&usg=AOvVaw02VKtHpw-Ne8pVIiOqz7Tr))

Once these values are properly defined, the Cell Census schema must reference to them

**Comment by atolopko-czi** [comment]
Dup of #21. Closing.
