### ISSUE TITLE
Add unit tests for builder

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#73]
The only way to test the builder currently is via a manual invocation on a small  corpus of H5ADs. 

Add some basic unit tests to assert success of an end-to-end "happy path" for the builder.

Runs tests from GHA workflow.

**Comment by pablo-gar** [comment]
Do we need to list a set of tests to include? Or is this issue self-explanatory to ensure the builder has enough unit test coverage?

**Comment by atolopko-czi** [comment]
> Do we need to list a set of tests to include? Or is this issue self-explanatory to ensure the builder has enough unit test coverage?

For now this issue is to just to get a _single_ unit that runs the whole builder, simply because we have _no_ unit tests currently. We relying primarily on the builder's own validation step to assert that the census is built correctly. This gets run by the builder by way of the unit test. And there are numerous validation checks in place now, to which we continue to add more.

That said, it would be worth a more comprehensive review of what the validator is asserting and _not_ asserting. If that's worthwhile, let's capture as a new (lower priority) issue?
