### ISSUE TITLE
change get_anndata() axis params  to tiledbsoma.AxisQuery 

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#80]
[Discussion](https://github.com/chanzuckerberg/cell-census/pull/77#discussion_r1083036031)

`cell_census.get_anndata.get_anndata()` currently takes the following params:
```
    obs_value_filter: Optional[str] = None,
    obs_coords: Tuple[SparseDFCoord, ...] = (slice(None),),
    var_value_filter: Optional[str] = None,
    var_coords: Tuple[SparseDFCoord, ...] = (slice(None),),
```

These params simply "flatten" the `AxisQuery()` constructor params, so we could just as well accept (just 2) `AxisQuery` params instead. This would make this CC API method's signature more consistent with the SOMA method signatures.

**Comment by pablo-gar** [comment]
@atolopko-czi I think this is ok to close because of #102 and #91. Thoughts?

**Comment by atolopko-czi** [comment]
I don't feel too strongly about this change, so I'm okay if you close it. 

Since one intent of CC API is to reduce the complexity of using SOMA (agreed?), keeping AxisQuery() out of the signature helps accomplish that.  A minor gain, but still a gain for the casual user that just wants an AnnData object. One could argue that if we changed this method's signature to take AxisQuery(), we might as well do away with the method entirely.

**Comment by bkmartinjr** [comment]
Has there been a resolution on this?  I can implement if you update the issue to reflect the intended direction.

**Comment by atolopko-czi** [comment]
@pablo-gar? I vote for do nothing.

**Comment by pablo-gar** [comment]
We can leave unchanged. There were recent PRs that addressed it tangentially as well. 

#117 Docstrings updated
#91 `obs_coords` and `var_coords` were added as arguments

https://github.com/chanzuckerberg/cell-census/pull/102#discussion_r1088944589
