### ISSUE TITLE
Investigate removed data in 2023-01-23 cell census build 

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#93]
Figure out why human data has fewer datasets and cells than in the previous build.

2023-01-23:
```
                     label      value
cell_census_schema_version      0.1.0
    cell_census_build_date 2023-01-23
          total_cell_count   46688297
         unique_cell_count   27578341
number_donors_homo_sapiens       9467
number_donors_mus_musculus       1296
             unique count
attribute          assays cell types     cells datasets tissues
organism
homo_sapiens           20        557  42766207      393     196
mus_musculus            9        211   3922090       77      45
```

Previous:
```
                     label      value
cell_census_schema_version      0.1.0
    cell_census_build_date 2023-01-13
          total_cell_count   47129886
         unique_cell_count   25213273
number_donors_homo_sapiens       9543
number_donors_mus_musculus       1296
             unique count
attribute          assays cell types     cells datasets tissues
organism
homo_sapiens           20        557  43207796      394     196
mus_musculus            9        211   3922090       77      45
```

**Comment by atolopko-czi** [comment]
Comparing the two cell census' sets of datasets, the newer census was found to be missing dataset `2a498ace-872a-4935-984b-1afa70fd9886`.  

Looking at Data Portal database, this dataset has been re-curated, changing its cells' assay type to `EFO:0030011` which is not a valid assay type per the [accepted list](https://github.com/chanzuckerberg/cell-census/blob/main/tools/cell_census_builder/globals.py#L176):
```
>>> ad1.obs.assay_ontology_term_id.value_counts()
EFO:0011025    422220
Name: assay_ontology_term_id, dtype: int64
>>> ad2.obs.assay_ontology_term_id.value_counts()
EFO:0030011    422220
Name: assay_ontology_term_id, dtype: int64
```
All of its cells were thus filtered out in the newer census build.

There were 47129886 - 46688297 = 441589 fewer cells in the newer census, which is _mostly_ accounted for by the 422220 cells that were filtered out for this dataset. Other datasets may have also been re-curated, explaining the discrepancy (we would need a dataset-by-dataset cell count comparison to confirm).

(This leaves one mystery, but which I think I can explain: The re-curated dataset `2a498ace-872a-4935-984b-1afa70fd9886` has a db created_at timestamp of `2023-01-25 09:36:22` (EST?), although the census build was done earlier on 2023-01-23. The portal's S3 `local.h5ad` is dated similarly `2023-01-25 04:54:29` (UTC) (`dataset_version_id = 469e771e-324b-493b-be6e-cfdfed96c77c`). But the newer census build retrieved the h5ad _before_ 2023-01-25, and is thus older than the h5ad stored by the the data portal on S3. And the h5ad that was used for the census build is not the same as the h5ad currently shown as the latest in the portal db, looking at its size alone. Since the Data Portal redesign was deployed on Monday and would have maintained all h5ad versions, I'm assuming a re-curation must have happened _after_ the 2023-01-13 census build, but _before_ the 2023-01-23 census build and was not captured by the new versioning system. Another re-curation must have occurred on 2023-01-25.)

Raw notes:
[troubleshoot-missing-data.txt](https://github.com/chanzuckerberg/cell-census/files/10504654/troubleshoot-missing-data.txt)

**Comment by atolopko-czi** [comment]
@pablo-gar I'll leave it on you to close this issue if you're satisfied with the explanation. If you're concerned that we do not have an _exact_ accounting of the cell count difference (since it was not perfectly explained by the 1 one missing dataset), I can look into it further. Though time is probably better spent on #97.  Also, any follow-up changes to the accepted assay types can be addressed in a new issue, as needed.

**Comment by pablo-gar** [comment]
I agree we can close this now and let's focus on finding ways to catch these cases in the future. These are turbulent times with almost no external users at the moment, so we don't have to dive deeper into this. 

Re-curation will happen in the future and this will likely affect differences in builds so spending time on #97 makes sense. Thanks for the thorough explanation @atolopko-czi
