### ISSUE TITLE
Report cell census changes between versions

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cell-census#97]
From one cell census version to another it would be useful to report changes between the builds, to catch potential errors in either data or processing:
* Datasets removed, added
* Datasets in both versions but that have differing cell counts
* Total cell count deltas by experiment (mouse, human)
* Deltas between `summary_cell_counts` dataframes
* Genes removed, added

As a starting point, see `tools/cell_census_builder/scripts/release/census_summary.py`

**Comment by pablo-gar** [comment]
Greatly support this and I'd would encourage to have this as part of the build process if possible.

Also related to #25
